import { Bell, Radio, RefreshCw, Send, Shield, Users } from "lucide-react";
import { useState } from "react";
import { trpc } from "@/lib/trpc";

function classNames(...values: Array<string | false | null | undefined>) { return values.filter(Boolean).join(" "); }

export default function AdminPushPanel() {
  const utils = trpc.useUtils();
  const subscribers = trpc.adminPush.subscribers.useQuery(undefined, { retry: false });
  const sendAlert = trpc.adminPush.send.useMutation({ onSuccess: () => { setFeedback("Alerta enviada correctamente."); setTitle(""); setDetail(""); void utils.adminPush.subscribers.invalidate(); } });
  const [title, setTitle] = useState("");
  const [detail, setDetail] = useState("");
  const [severity, setSeverity] = useState<"info" | "success" | "warning" | "urgent">("info");
  const [target, setTarget] = useState("all");
  const [feedback, setFeedback] = useState("");
  const rows = subscribers.data ?? [];
  const uniqueUsers = Array.from(new Map(rows.map((row) => [row.userId, row])).values());
  const submit = () => { if (!title.trim() || !detail.trim() || sendAlert.isPending) return; setFeedback(""); sendAlert.mutate({ title: title.trim(), detail: detail.trim(), severity, targetUserId: target === "all" ? null : Number(target) }); };

  return <div>
    <div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="eyebrow mb-2">Seguridad · administración</div><h1 className="font-display text-4xl font-bold uppercase leading-none tracking-tight text-white md:text-5xl">Centro de alertas</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#93a1b2]">Gestiona las suscripciones Push activas y envía avisos importantes al equipo desde un espacio restringido a administradores.</p></div><div className="flex items-center gap-2 rounded-lg border border-[#456c30] bg-[#172817] px-3 py-2 text-xs font-bold uppercase tracking-[.1em] text-[#b9ff78]"><Shield className="h-4 w-4" /> Solo admin</div></div>
    <div className="mb-4 grid gap-3 sm:grid-cols-3"><div className="panel p-4"><div className="eyebrow">Suscripciones</div><div className="mt-3 font-display text-3xl font-bold text-white">{rows.length}</div><div className="mt-1 text-xs text-[#73b2ff]">dispositivos registrados</div></div><div className="panel p-4"><div className="eyebrow">Personas</div><div className="mt-3 font-display text-3xl font-bold text-white">{uniqueUsers.length}</div><div className="mt-1 text-xs text-[#d2a8ff]">cuentas con Push</div></div><div className="panel p-4"><div className="eyebrow">Estado</div><div className="mt-3 flex items-center gap-2 font-display text-2xl font-bold text-[#b9ff78]"><span className="h-2.5 w-2.5 rounded-full bg-[#a8ff2a] shadow-[0_0_10px_#a8ff2a]" /> Activo</div><div className="mt-1 text-xs text-[#8291a4]">VAPID configurado</div></div></div>
    <div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><div className="panel p-5 md:p-6"><div className="mb-5 flex items-center justify-between"><div><div className="eyebrow mb-2">Compositor</div><h2 className="font-display text-2xl font-bold uppercase text-white">Enviar alerta Push</h2></div><Radio className="h-5 w-5 text-[#9b3dff]" /></div><div className="space-y-3"><label className="block"><span className="eyebrow mb-2 block text-[#d2a8ff]">Destinatario</span><select value={target} onChange={(event) => setTarget(event.target.value)} className="focus-ring w-full rounded-lg border border-[#2c3c50] bg-[#0a1018] px-3 py-2.5 text-sm text-white"><option value="all">Todos los suscriptores ({rows.length})</option>{uniqueUsers.map((row) => <option key={row.userId} value={row.userId}>{row.name} · {row.email}</option>)}</select></label><label className="block"><span className="eyebrow mb-2 block text-[#d2a8ff]">Título</span><input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={120} placeholder="Ej. Scrim confirmado para hoy" className="focus-ring w-full rounded-lg border border-[#2c3c50] bg-[#0a1018] px-3 py-2.5 text-sm text-white placeholder:text-[#637287]" /></label><label className="block"><span className="eyebrow mb-2 block text-[#d2a8ff]">Mensaje</span><textarea value={detail} onChange={(event) => setDetail(event.target.value)} maxLength={1000} rows={4} placeholder="Escribe el aviso que aparecerá en el navegador..." className="focus-ring w-full resize-none rounded-lg border border-[#2c3c50] bg-[#0a1018] px-3 py-2.5 text-sm text-white placeholder:text-[#637287]" /></label><div className="grid gap-3 sm:grid-cols-[1fr_auto] sm:items-end"><label className="block"><span className="eyebrow mb-2 block text-[#d2a8ff]">Prioridad</span><select value={severity} onChange={(event) => setSeverity(event.target.value as typeof severity)} className={classNames("focus-ring w-full rounded-lg border bg-[#0a1018] px-3 py-2.5 text-sm", severity === "urgent" ? "border-[#74303b] text-[#ff8994]" : severity === "warning" ? "border-[#704523] text-[#ffad69]" : "border-[#2c3c50] text-white")}><option value="info">Informativa</option><option value="success">Éxito</option><option value="warning">Advertencia</option><option value="urgent">Urgente</option></select></label><button onClick={submit} disabled={sendAlert.isPending || !title.trim() || !detail.trim() || rows.length === 0} className="focus-ring inline-flex items-center justify-center gap-2 rounded-lg bg-[#9b3dff] px-4 py-2.5 text-xs font-bold uppercase tracking-[.1em] text-white disabled:cursor-not-allowed disabled:opacity-50"><Send className="h-4 w-4" /> {sendAlert.isPending ? "Enviando..." : "Enviar alerta"}</button></div>{sendAlert.error && <p className="mt-3 text-xs text-[#ff8994]">{sendAlert.error.message}</p>}{feedback && <p className="mt-3 text-xs text-[#b9ff78]">{feedback}</p>}</div></div>
    <div className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-[#202e3e] bg-[#101724] px-5 py-4"><div><div className="eyebrow mb-1 text-[#73b2ff]">Audiencia Push</div><h2 className="font-display text-2xl font-bold uppercase text-white">Suscriptores</h2></div><button onClick={() => void subscribers.refetch()} className="focus-ring rounded-lg border border-[#2c3c50] p-2 text-[#93a1b2] hover:text-white" aria-label="Actualizar suscriptores"><RefreshCw className={classNames("h-4 w-4", subscribers.isFetching && "animate-spin")} /></button></div><div className="divide-y divide-[#1c2938]">{subscribers.isLoading && <div className="p-5 text-sm text-[#9caabd]">Cargando suscriptores...</div>}{subscribers.error && <div className="p-5 text-sm text-[#ff8994]">No tienes permisos para ver este panel.</div>}{!subscribers.isLoading && !rows.length && <div className="p-5 text-sm text-[#9caabd]">Todavía no hay dispositivos suscritos.</div>}{rows.map((row) => <div key={row.id} className="flex items-center gap-3 px-5 py-4"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#102640] text-[#73b2ff]"><Users className="h-4 w-4" /></span><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold text-white">{row.name}</div><div className="truncate text-xs text-[#8291a4]">{row.email} · {new Date(row.subscribedAt).toLocaleString("es-VE", { dateStyle: "medium", timeStyle: "short" })}</div></div><Bell className="h-4 w-4 text-[#9b3dff]" /></div>)}</div></div></div></div>;
}
